---

- name: "Install gawk"
  become: yes
  apt: pkg=gawk
       state=present
       update_cache=yes
       cache_valid_time=3600

- name: "rsync testssl.sh"
  synchronize: src=testssl.sh dest=/usr/local/share/

- name: "rsync mit-testssl.sh"
  synchronize: src=mit-testssl.sh dest=/usr/lib/zabbix/externalscripts/mit-testssl.sh

# //TODO: Increase timeout in /etc/zabbix/zabbix_server.conf to 30sec
