---

- name: "rsync testssl.sh (directory, distribution)"
  become: yes
  synchronize: 
    src: testssl.sh
    dest: /usr/local/share/
    delete: yes
    rsync_opts:
      - "--exclude=.git"

- name: "rsync mit-testssl.sh (Zabbix wrapper script)"
  become: yes
  synchronize: src=mit-testssl.sh dest=/usr/lib/zabbix/externalscripts/mit-testssl.sh

